name: Publish Go Bindings

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish-go:
    name: Publish Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: true

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Go protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.12
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.2

      - name: Generate Go Protobuf
        run: bash ./scripts/generate_go.sh
